
/// <reference types="cypress" />

describe('Checking check-out Funcionality',function(){
  
    it('verifying pay by bankwire option', function(){
      cy.visit('http://automationpractice.com/index.php')
      cy.contains('Add to cart').click()
      cy.wait(3000)
      cy.contains('Proceed to checkout').click()
      cy.title().should('eq',"Order - My Store")
      cy.get('#total_price').contains('$18.51')
      cy.wait(3000)
      cy.get('a.standard-checkout[title="Proceed to checkout"]').click()
      cy.wait(3000)
      cy.get('#email').type('abd.akti@gmail.com')  
      cy.get('#passwd').type('aktikadir') 
      cy.get('#SubmitLogin').click()
      cy.wait(3000)
      cy.get('button.button-medium[type="submit"]').click()
      cy.wait(3000)
      cy.get('#cgv').check()
      cy.get('button.button-medium[type="submit"]').click()
      cy.wait(3000)
      cy.get('a.bankwire').click()
      cy.get('button.button-medium[type="submit"]').click()
      cy.get('h1.page-heading').should('be.visible')
})
it('verifying pay by check option', function(){
      cy.visit('http://automationpractice.com/index.php')
      cy.contains('Add to cart').click()
      cy.wait(3000)
      cy.contains('Proceed to checkout').click()
      cy.title().should('eq',"Order - My Store")
      cy.get('#total_price').contains('$18.51')
      cy.wait(3000)
      cy.get('a.standard-checkout[title="Proceed to checkout"]').click()
      cy.wait(3000)
      cy.get('#email').type('abd.akti@gmail.com')  
      cy.get('#passwd').type('aktikadir') 
      cy.get('#SubmitLogin').click()
      cy.wait(3000)
      cy.get('button.button-medium[type="submit"]').click()
      cy.wait(3000)
      cy.get('#cgv').check()
      cy.get('button.button-medium[type="submit"]').click()
      cy.wait(3000)
      cy.get('a.cheque').click()
      cy.get('button.button-medium[type="submit"]').click()
      cy.get('h1.page-heading').should('be.visible')
})
})